const APPROVED_ROLES = Object.freeze([
  'ADMIN',
  'RECRUITER',
  'HIRING_MANAGER',
  'INTERVIEWER',
]);

export const ORGANIZATION_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  RECRUITER: 'RECRUITER',
  HIRING_MANAGER: 'HIRING_MANAGER',
  INTERVIEWER: 'INTERVIEWER',
});

export const PERMISSIONS = Object.freeze({
  MEMBER_READ: 'member:read',
  MEMBER_INVITE: 'member:invite',
  MEMBER_ROLE_CHANGE: 'member:role-change',
  MEMBER_REMOVE: 'member:remove',
  INVITATION_READ: 'invitation:read',
  INVITATION_REVOKE: 'invitation:revoke',
  JOB_LIST: 'job:list',
  JOB_READ: 'job:read',
  JOB_CREATE: 'job:create',
  JOB_UPDATE: 'job:update',
  JOB_OPEN: 'job:open',
  JOB_CLOSE: 'job:close',
  JOB_REOPEN: 'job:reopen',
  JOB_ARCHIVE: 'job:archive',
  PIPELINE_VIEW: 'pipeline:view',
  PIPELINE_CONFIGURE: 'pipeline:configure',
  APPLICATION_FORM_VIEW: 'application-form:view',
  APPLICATION_FORM_CONFIGURE: 'application-form:configure',
  CANDIDATE_LIST: 'candidate:list',
  CANDIDATE_READ: 'candidate:read',
  CANDIDATE_DOCUMENT_ACCESS: 'candidate-document:access',
  INTERVIEW_CREATE: 'interview:create',
  INTERVIEW_VIEW: 'interview:view',
  INTERVIEW_VIEW_ASSIGNED: 'interview:view-assigned',
  INTERVIEW_UPDATE: 'interview:update',
  INTERVIEW_RESCHEDULE: 'interview:reschedule',
  INTERVIEW_CANCEL: 'interview:cancel',
  SCORECARD_TEMPLATE_VIEW: 'scorecard-template:view',
  SCORECARD_TEMPLATE_MANAGE: 'scorecard-template:manage',
  SCORECARD_VIEW_SUBMITTED: 'scorecard:view-submitted',
  SCORECARD_COMPLETE: 'scorecard:complete',
  APPLICATION_NOTE_MANAGE: 'application-note:manage',
  COMMUNICATION_VIEW: 'communication:view',
  COMMUNICATION_SEND: 'communication:send',
  COMMUNICATION_TEMPLATE_VIEW: 'communication-template:view',
  COMMUNICATION_TEMPLATE_MANAGE: 'communication-template:manage',
  NOTIFICATION_VIEW_OWN: 'notification:view-own',
  NOTIFICATION_READ_OWN: 'notification:read-own',
  NOTIFICATION_PREFERENCE_MANAGE_OWN: 'notification-preference:manage-own',
  OFFER_VIEW: 'offer:view',
  OFFER_CREATE: 'offer:create',
  OFFER_UPDATE: 'offer:update',
  OFFER_REVISE: 'offer:revise',
  OFFER_SEND: 'offer:send',
  OFFER_RECORD_ACCEPTANCE: 'offer:record-acceptance',
  OFFER_RECORD_DECLINE: 'offer:record-decline',
  OFFER_WITHDRAW: 'offer:withdraw',
  APPLICATION_HIRE: 'application:hire',
  APPLICATION_REJECT: 'application:reject',
  APPLICATION_REOPEN: 'application:reopen',
  TALENT_POOL_VIEW: 'talent-pool:view',
  TALENT_POOL_MANAGE: 'talent-pool:manage',
  TALENT_POOL_MEMBER_MANAGE: 'talent-pool-member:manage',
});

const ADMIN_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));
const JOB_MANAGER_PERMISSIONS = Object.freeze([
  PERMISSIONS.JOB_LIST,
  PERMISSIONS.JOB_READ,
  PERMISSIONS.JOB_CREATE,
  PERMISSIONS.JOB_UPDATE,
  PERMISSIONS.JOB_OPEN,
  PERMISSIONS.JOB_CLOSE,
  PERMISSIONS.JOB_REOPEN,
  PERMISSIONS.PIPELINE_VIEW,
]);

// Keep this matrix in application code until product and security decisions
// justify database-backed permissions.
export const ROLE_PERMISSIONS = Object.freeze({
  ADMIN: ADMIN_PERMISSIONS,
  RECRUITER: Object.freeze([
    ...JOB_MANAGER_PERMISSIONS,
    PERMISSIONS.JOB_ARCHIVE,
    PERMISSIONS.PIPELINE_CONFIGURE,
    PERMISSIONS.APPLICATION_FORM_VIEW,
    PERMISSIONS.APPLICATION_FORM_CONFIGURE,
    PERMISSIONS.CANDIDATE_LIST,
    PERMISSIONS.CANDIDATE_READ,
    PERMISSIONS.CANDIDATE_DOCUMENT_ACCESS,
    PERMISSIONS.INTERVIEW_CREATE,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_VIEW_ASSIGNED,
    PERMISSIONS.INTERVIEW_UPDATE,
    PERMISSIONS.INTERVIEW_RESCHEDULE,
    PERMISSIONS.INTERVIEW_CANCEL,
    PERMISSIONS.SCORECARD_TEMPLATE_VIEW,
    PERMISSIONS.SCORECARD_TEMPLATE_MANAGE,
    PERMISSIONS.SCORECARD_VIEW_SUBMITTED,
    PERMISSIONS.SCORECARD_COMPLETE,
    PERMISSIONS.APPLICATION_NOTE_MANAGE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_TEMPLATE_VIEW,
    PERMISSIONS.COMMUNICATION_TEMPLATE_MANAGE,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_READ_OWN,
    PERMISSIONS.NOTIFICATION_PREFERENCE_MANAGE_OWN,
    PERMISSIONS.OFFER_VIEW,
    PERMISSIONS.OFFER_CREATE,
    PERMISSIONS.OFFER_UPDATE,
    PERMISSIONS.OFFER_REVISE,
    PERMISSIONS.OFFER_SEND,
    PERMISSIONS.OFFER_RECORD_ACCEPTANCE,
    PERMISSIONS.OFFER_RECORD_DECLINE,
    PERMISSIONS.OFFER_WITHDRAW,
    PERMISSIONS.APPLICATION_HIRE,
    PERMISSIONS.APPLICATION_REJECT,
    PERMISSIONS.APPLICATION_REOPEN,
    PERMISSIONS.TALENT_POOL_VIEW,
    PERMISSIONS.TALENT_POOL_MANAGE,
    PERMISSIONS.TALENT_POOL_MEMBER_MANAGE,
  ]),
  // Hiring Managers retain the same read scope as JOB_READ: they can inspect
  // a job's current application configuration, but cannot configure it.
  HIRING_MANAGER: Object.freeze([
    ...JOB_MANAGER_PERMISSIONS,
    PERMISSIONS.APPLICATION_FORM_VIEW,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_VIEW_ASSIGNED,
    PERMISSIONS.SCORECARD_TEMPLATE_VIEW,
    PERMISSIONS.SCORECARD_VIEW_SUBMITTED,
    PERMISSIONS.SCORECARD_COMPLETE,
    PERMISSIONS.APPLICATION_NOTE_MANAGE,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_READ_OWN,
    PERMISSIONS.NOTIFICATION_PREFERENCE_MANAGE_OWN,
  ]),
  INTERVIEWER: Object.freeze([
    PERMISSIONS.INTERVIEW_VIEW_ASSIGNED,
    PERMISSIONS.SCORECARD_COMPLETE,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_READ_OWN,
    PERMISSIONS.NOTIFICATION_PREFERENCE_MANAGE_OWN,
  ]),
});

const KNOWN_PERMISSIONS = new Set(Object.values(PERMISSIONS));

export function hasPermission({ role, permission } = {}) {
  if (!APPROVED_ROLES.includes(role) || !KNOWN_PERMISSIONS.has(permission)) {
    return false;
  }

  return ROLE_PERMISSIONS[role].includes(permission);
}
