-- Phase 11 application-form configuration foundation. IDs are generated by
-- application UUIDv7 for new records; this migration uses a deterministic
-- UUIDv7-shaped mapper only for historical Job backfill.
CREATE TYPE "ApplicationFormVersionStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "ApplicationFormQuestionType" AS ENUM (
  'SHORT_TEXT', 'LONG_TEXT', 'NUMBER', 'YES_NO', 'SINGLE_SELECT',
  'MULTI_SELECT', 'DATE', 'URL'
);

-- The active-version FK is added after both sides exist. It is deferrable so
-- the Job creation transaction can atomically insert the form (with its V1
-- active ID) and the V1 row in either safe statement order.
CREATE TABLE "ApplicationForm" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "jobId" UUID NOT NULL,
  "activeVersionId" UUID,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "ApplicationForm_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ApplicationForm_jobId_key" UNIQUE ("jobId")
);

CREATE TABLE "ApplicationFormVersion" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "applicationFormId" UUID NOT NULL,
  "versionNumber" INTEGER NOT NULL,
  "status" "ApplicationFormVersionStatus" NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "publishedAt" TIMESTAMPTZ(6),
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "ApplicationFormVersion_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ApplicationFormVersion_applicationFormId_versionNumber_key"
    UNIQUE ("applicationFormId", "versionNumber"),
  CONSTRAINT "ApplicationFormVersion_versionNumber_check" CHECK ("versionNumber" > 0),
  CONSTRAINT "ApplicationFormVersion_revision_check" CHECK ("revision" > 0),
  CONSTRAINT "ApplicationFormVersion_publication_check" CHECK (
    ("status" = 'DRAFT' AND "publishedAt" IS NULL)
    OR ("status" = 'PUBLISHED' AND "publishedAt" IS NOT NULL)
  )
);

CREATE TABLE "ApplicationFormQuestion" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "applicationFormVersionId" UUID NOT NULL,
  "questionKey" VARCHAR(100) NOT NULL,
  "type" "ApplicationFormQuestionType" NOT NULL,
  "label" VARCHAR(500) NOT NULL,
  "description" TEXT,
  "placeholder" VARCHAR(500),
  "required" BOOLEAN NOT NULL DEFAULT FALSE,
  "sortOrder" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "ApplicationFormQuestion_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ApplicationFormQuestion_applicationFormVersionId_questionKey_key"
    UNIQUE ("applicationFormVersionId", "questionKey"),
  CONSTRAINT "ApplicationFormQuestion_sortOrder_check" CHECK ("sortOrder" > 0)
);

CREATE TABLE "ApplicationFormQuestionOption" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "questionId" UUID NOT NULL,
  "label" VARCHAR(500) NOT NULL,
  "value" VARCHAR(200) NOT NULL,
  "sortOrder" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "ApplicationFormQuestionOption_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ApplicationFormQuestionOption_questionId_value_key"
    UNIQUE ("questionId", "value"),
  CONSTRAINT "ApplicationFormQuestionOption_sortOrder_check" CHECK ("sortOrder" > 0)
);

CREATE INDEX "ApplicationForm_organizationId_jobId_idx"
  ON "ApplicationForm" ("organizationId", "jobId");
CREATE INDEX "ApplicationFormVersion_applicationFormId_status_idx"
  ON "ApplicationFormVersion" ("applicationFormId", "status");
CREATE INDEX "ApplicationFormQuestion_applicationFormVersionId_sortOrder_idx"
  ON "ApplicationFormQuestion" ("applicationFormVersionId", "sortOrder");
CREATE INDEX "ApplicationFormQuestionOption_questionId_sortOrder_idx"
  ON "ApplicationFormQuestionOption" ("questionId", "sortOrder");

-- Prisma cannot express this partial unique index. It guarantees at most one
-- editable draft while allowing any number of historical published snapshots.
CREATE UNIQUE INDEX "ApplicationFormVersion_one_draft_per_form_key"
  ON "ApplicationFormVersion" ("applicationFormId")
  WHERE "status" = 'DRAFT';

ALTER TABLE "ApplicationForm"
  ADD CONSTRAINT "ApplicationForm_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationForm"
  ADD CONSTRAINT "ApplicationForm_jobId_fkey"
  FOREIGN KEY ("jobId") REFERENCES "Job"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormVersion"
  ADD CONSTRAINT "ApplicationFormVersion_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormVersion"
  ADD CONSTRAINT "ApplicationFormVersion_applicationFormId_fkey"
  FOREIGN KEY ("applicationFormId") REFERENCES "ApplicationForm"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormQuestion"
  ADD CONSTRAINT "ApplicationFormQuestion_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormQuestion"
  ADD CONSTRAINT "ApplicationFormQuestion_applicationFormVersionId_fkey"
  FOREIGN KEY ("applicationFormVersionId") REFERENCES "ApplicationFormVersion"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormQuestionOption"
  ADD CONSTRAINT "ApplicationFormQuestionOption_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "ApplicationFormQuestionOption"
  ADD CONSTRAINT "ApplicationFormQuestionOption_questionId_fkey"
  FOREIGN KEY ("questionId") REFERENCES "ApplicationFormQuestion"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE FUNCTION "application_form_uuidv7_from_seed"(seed TEXT, occurred_at TIMESTAMPTZ)
RETURNS UUID LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  timestamp_hex TEXT := lpad(to_hex(floor(extract(epoch FROM occurred_at) * 1000)::BIGINT), 12, '0');
  digest TEXT := md5(seed);
  variant TEXT := substr('89ab', (ascii(substr(digest, 4, 1)) % 4) + 1, 1);
BEGIN
  RETURN format('%s-%s-%s-%s-%s', substr(timestamp_hex, 1, 8),
    substr(timestamp_hex, 9, 4), '7' || substr(digest, 1, 3),
    variant || substr(digest, 5, 3), substr(digest, 8, 12))::UUID;
END;
$$;

-- Existing Jobs receive exactly one empty, published V1. The anti-join is
-- recovery-safe and all linked IDs derive deterministically from the Job.
INSERT INTO "ApplicationForm" ("id", "organizationId", "jobId", "createdAt", "updatedAt")
SELECT "application_form_uuidv7_from_seed"('application-form:' || j."id"::TEXT, j."createdAt"),
  j."organizationId", j."id", j."createdAt", j."updatedAt"
FROM "Job" j
LEFT JOIN "ApplicationForm" f ON f."jobId" = j."id"
WHERE f."id" IS NULL;

INSERT INTO "ApplicationFormVersion" (
  "id", "organizationId", "applicationFormId", "versionNumber", "status", "revision",
  "publishedAt", "createdAt", "updatedAt"
)
SELECT "application_form_uuidv7_from_seed"('application-form-version:' || f."jobId"::TEXT || ':1', f."createdAt"),
  f."organizationId", f."id", 1, 'PUBLISHED', 1, f."createdAt", f."createdAt", f."updatedAt"
FROM "ApplicationForm" f
LEFT JOIN "ApplicationFormVersion" v
  ON v."applicationFormId" = f."id" AND v."versionNumber" = 1
WHERE v."id" IS NULL;

UPDATE "ApplicationForm" f
SET "activeVersionId" = v."id"
FROM "ApplicationFormVersion" v
WHERE v."applicationFormId" = f."id" AND v."versionNumber" = 1
  AND f."activeVersionId" IS NULL;

DROP FUNCTION "application_form_uuidv7_from_seed"(TEXT, TIMESTAMPTZ);

ALTER TABLE "ApplicationForm" ALTER COLUMN "activeVersionId" SET NOT NULL;
ALTER TABLE "ApplicationForm" ADD CONSTRAINT "ApplicationForm_activeVersionId_key"
  UNIQUE ("activeVersionId");
ALTER TABLE "ApplicationForm" ADD CONSTRAINT "ApplicationForm_activeVersionId_fkey"
  FOREIGN KEY ("activeVersionId") REFERENCES "ApplicationFormVersion"("id")
  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED;
